---

version: '3.4'

services:
  db:
    volumes:
      - type: bind
        source: ./tmp
        target: /tmp
  twlight:
    image: quay.io/wikipedialibrary/twlight:local
    build:
      context: .
    env_file:
      - ./conf/travis.twlight.env
    environment:
      - TRAVIS_JOB_ID
      - TRAVIS_BRANCH
      - COVERALLS_REPO_TOKEN
